baseURL = 'https://ericarellano.tech'
languageCode = 'en-us'
title = "Eric's Software Engineering Blog"
timezone = 'America/Los_Angeles'
themesDir = "../themes"
theme = "PaperMod"
enableEmoji = true
buildFuture = true

[markup.goldmark.extensions.emoji]
  src = "https://github.githubassets.com/images/icons/emoji/"
  size = 20  # Optional: Adjust the size in pixels
  class = "emoji"  # Optional: Add a CSS class for styling

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  subtitle = 'Software Engineering, AI and Cloud'
  enableSearch = true
  author = 'Eric Arellano'
  copyright = 'Â©2026'
  description = "Musings and snippets of Go, Python, Devops, AI"
  keywords = ["Go", "Python", "AI", "DevOps", "AWS", "GCP", "Cloud Architecture", "Software Engineering"]

[params.profileMode]
  enabled = true
  title = "Hi, I'm Eric Arellano"
  imageUrl = "/images/author.jpg"  # Optional: Path to your profile image
  imageWidth = 120  # Optional: Image width in pixels
  imageHeight = 120  # Optional: Image height in pixels
  color = 'auto'
  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostMeta = true

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts"

[[params.profileMode.buttons]]
  name = "About"
  url = "/about"


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/chukiagosoftware"
[[params.socialIcons]]
  name = "linkedin"
  url = 'https://www.linkedin.com/in/eric-arellano-martinez/'

[[params.links]]
  name = 'X'
  url = 'https://x.com'
[[params.links]]
  name = 'OpenAI'
  url = 'https://www.openai.com'
[[params.links]]
  name = 'Claude'
  url = 'https://www.anthropic.com'

[pagination]
  pagerSize = 10

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 20

[[menu.main]]
  name = "Search"
  url = "/search"
  weight = 30

