baseURL = 'https://blog.ericarellano.tech'
languageCode = 'en-us'
title = 'Another Software Engineering Blog'
timezone = 'America/Los_Angeles'
themesDir = "../themes"
theme = "PaperMod"
enableEmoji = true
buildFuture = true

[markup.goldmark.extensions.emoji]
  src = "https://github.githubassets.com/images/icons/emoji/"
  size = 20  # Optional: Adjust the size in pixels
  class = "emoji"  # Optional: Add a CSS class for styling


[params]
  subtitle = 'Software Engineering, AI and Cloud'
  author = 'Eric Arellano'
  copyright = 'Â©2026'
  description = "Musings and snippets of Go, Python, Devops, AI"
  keywords = ["Go", "Python", "AI", "DevOps", "AWS", "GCP", "Cloud Architecture", "Software Engineering"]
  [params.search]
    enabled = true
    contentLength = 4000  # Optional: Truncate long previews
    placeholder = "Search..."  # Optional: Custom placeholder text
  [params.profileMode]
   enabled = true
   title = "Hi, I'm Eric Arellano"
   imageUrl = "/images/author.jpg"  # Optional: Path to your profile image
   imageWidth = 120  # Optional: Image width in pixels
   imageHeight = 120  # Optional: Image height in pixels
   color = 'auto'
    # Show reading time, word count, etc.
   ShowReadingTime = true
   ShowWordCount = true
   ShowShareButtons = true
   ShowPostNavLinks = true
   ShowBreadCrumbs = true
   ShowCodeCopyButtons = true
   ShowPostMeta = true

[params.social]
  github = 'https://github.com/chukiagosoftware'
  linkedin = 'https://www.linkedin.com/in/eric-arellano-martinez/'

[[params.links]]
  name = 'X'
  url = 'https://x.com'
[[params.links]]
  name = 'OpenAI'
  url = 'https://www.openai.com'
[[params.links]]
  name = 'Claude'
  url = 'https://www.anthropic.com'

[pagination]
  pagerSize = 10

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 20

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 10