baseURL = 'https://blog.ericarellano.tech'
languageCode = 'en-us'
title = 'Go, Python, AI, Devops, AWS, GCP, Cloud Architecture'
timezone = 'America/Los_Angeles'
themesDir = "../themes"
theme = "PaperMod"
enableEmoji = true
buildFuture = true

[params]
  subtitle = 'Software Engineering, AI and Cloud'
  author = 'Eric Arellano'
  copyright = 'Â©2026'

[params.social]
  github = 'https://github.com/chukiagosoftware'
  linkedin = 'https://www.linkedin.com/in/eric-arellano-martinez/'

[[params.links]]
  name = 'X'
  url = 'https://x.com'
[[params.links]]
  name = 'OpenAI'
  url = 'https://www.openai.com'
[[params.links]]
  name = 'Claude'
  url = 'https://www.anthropic.com'

[pagination]
  pagerSize = 10

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 20

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 10